### PR TITLE
Proxy settings can be added now

### PR DESCRIPTION
**Pull request by thealphadollar**
#3 I've added the code to ask the user if he wants to add a proxy (only in the terminal version not GUI), and those proxy settings are used for the incoming and outgoing traffic.
I'm currently not behind a proxy and hence was not able to test this but theoretically, it should work.

### CODE REVIEW

**Comment by thealphadollar** [comment]
merge conflicts resolved, please check @ashishkg0022

**Comment by ashishkg0022** [comment]
I am currently not using net under proxy . please wait for a week , I will test it.

**Comment by thealphadollar** [comment]
@ashishkg0022 please check this now?

**Comment by ashishkg0022** [comment]
Sorry for the delay. I have tested it and it is not working
```
File "ga-cli.py", line 98, in <module>
    M = imaplib.IMAP4_SSL('imap.gmail.com')
  File "/usr/lib/python2.7/imaplib.py", line 1166, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python2.7/imaplib.py", line 173, in __init__
    self.open(host, port)
  File "/usr/lib/python2.7/imaplib.py", line 1177, in open
    self.sock = socket.create_connection((host, port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 101] Network is unreachable
```

**Comment by thealphadollar** [comment]
The error hasn't been resolved and I'm unable to rectify it.

**Pull request closed without merging**
